name: Workflow 2

on:
  workflow_run:
    workflows: ["Workflow 1"]
    types: [completed]
    branches: [main]

jobs:
  print-text:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Print workflow message
        run: echo "Workflow 2 runs after Workflow 1 succeeded"
